AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  UserName:
    Type: String
    Description: The name of the IAM user
    Default: awsnotes
  PolicyName:
    Type: String
    Description: The name of the IAM policy
    Default: developer-policy
  RoleName:
    Type: String
    Description: The name of the IAM role
    Default: awsnotes-developer-role
  GroupName:
    Type: String
    Description: The name of the IAM group
    Default: developer-group

Resources:
  DeveloperRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      RoleName: !Ref RoleName
      # The trust policy allows the role to be assumed by the specified services
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: Allow
            Principal: 
              Service: 
                - ec2.amazonaws.com
                - lambda.amazonaws.com
                - ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies: 
        - PolicyName: !Ref PolicyName
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: Allow
                Action: 
                  - 'ec2:*'
                  - 's3:*'
                  - 'dynamodb:*'
                  - 'lambda:*'
                  - 'rds:*'
                  - 'cloudwatch:*'
                  - 'logs:*'
                  - 'sns:*'
                  - 'sqs:*'
                  - 'ecs:*'
                  - 'ecr:*'
                  - 'eks:*'
                  - 'cloudformation:*'
                  - 'iam:PassRole'
                Resource: '*'
              - Effect: Deny
                Action: 
                  - 'aws-portal:*'
                  - 'budgets:*'
                  - 'ce:*'
                  - 'cur:*'
                  - 'support:*'
                  - 'organizations:*'
                  - 'account:*'
                  - 'billing:*'
                Resource: '*'

  # Create a group and attach the policy to the group
  DeveloperGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: !Ref GroupName
      Policies:
        - PolicyName: !Ref PolicyName
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: !GetAtt DeveloperRole.Arn

  # Create a user
  DeveloperUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Ref UserName

  # Attach the user to the group
  AttachDeveloperUserToGroup:
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
      GroupName: !Ref GroupName
      Users:
        - !Ref DeveloperUser
    DependsOn: DeveloperGroup