AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Admin API for administrative tasks"

Parameters:
  RootStackName:
    Type: String
    Description: "Name of the root stack, used for constructing resource names."
  ProgrammesTableName:
    Type: String
    Description: "Name of the DynamoDB table for programmes."
  ProgrammesTableArn:
    Type: String
    Description: "ARN of the DynamoDB table for programmes."

Resources:
  AdminLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${RootStackName}-AdminLambdaRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AdminLambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${RootStackName}-AdminLambda:*"
        - PolicyName: AdminLambdaDynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeTable
                  - dynamodb:ListTables
                Resource: !Ref ProgrammesTableArn
        - PolicyName: AdminLambdaInvokeOtherLambdas
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function/${RootStackName}-periodic-reference-PeriodicReferenceApp"
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function/${RootStackName}-userprefs-title-ingestion-UserPrefsTitleIngestionApp"
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function/${RootStackName}-title-enrichment-TitleEnrichmentApp"

  AdminLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${RootStackName}-AdminLambda"
      CodeUri: ../../src/admin_lambda/
      Handler: admin_lambda.lambda_handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt AdminLambdaExecutionRole.Arn
      Environment:
        Variables:
          PROGRAMMES_TABLE_NAME: !Ref ProgrammesTableName
          PROGRAMMES_TABLE_ARN: !Ref ProgrammesTableArn
          REFERENCE_DATA_LAMBDA_NAME: !Sub "${RootStackName}-periodic-reference-PeriodicReferenceApp"
          TITLE_DATA_REFRESH_LAMBDA_NAME: !Sub "${RootStackName}-userprefs-title-ingestion-UserPrefsTitleIngestionApp"
          TITLE_ENRICHMENT_LAMBDA_NAME: !Sub "${RootStackName}-title-enrichment-TitleEnrichmentApp"
      Events:
        AdminApiGetSummary:
          Type: Api
          Properties:
            Path: /admin/system/dynamodb/summary
            Method: get
            RestApiId: !Ref ServerlessRestApi
        AdminApiPostReferenceRefresh:
          Type: Api
          Properties:
            Path: /admin/data/reference/refresh
            Method: post
            RestApiId: !Ref ServerlessRestApi
        AdminApiPostTitleRefresh:
          Type: Api
          Properties:
            Path: /admin/data/titles/refresh
            Method: post
            RestApiId: !Ref ServerlessRestApi
        AdminApiPostTitleEnrich:
          Type: Api
          Properties:
            Path: /admin/data/titles/enrich
            Method: post
            RestApiId: !Ref ServerlessRestApi

  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'" # Adjust for security

Outputs:
  ApiEndpoint:
    Description: "The Admin API endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
