AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Root SAM application for the Event Streaming App.

Parameters:
  ProgrammesTableName:
    Type: String
    Description: Name of the DynamoDB table for programmes.
    Default: UKTVProgrammes
  WatchModeApiKey:
    Type: String
    NoEcho: true
    Description: "The API key for WatchMode API (will be stored in Secrets Manager)"
  WatchModeHostname:
    Type: String
    Description: "The Hostname for WatchMode API"
    Default: "https://api.watchmode.com"
  TestUserName:
    Type: String
    Description: "The username of the pre-created test user"
    Default: "test.user@example.com"
  CreateDataStream:
    Type: String
    Description: "Set to 'true' to create the Kinesis Data Stream."
    Default: "false"
    AllowedValues: [ "true", "false" ]

Conditions:
  ShouldCreateDataStream: !Equals [ !Ref CreateDataStream, "true" ]

Resources:
  WatchModeApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${AWS::StackName}/WatchModeApiKey"
      Description: API key for WatchMode API
      SecretString: !Ref WatchModeApiKey

  ProgrammesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref ProgrammesTableName
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  ProgrammeDataStream:
    Type: AWS::Kinesis::Stream
    Condition: ShouldCreateDataStream
    Properties:
      StreamModeDetails:
        StreamMode: ON_DEMAND
      RetentionPeriodHours: 24

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-website-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "OAI for ${AWS::StackName}"

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"

  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "CloudFront distribution for ${AWS::StackName} website"
        DefaultRootObject: index.html
        Origins:
          - Id: !Sub "S3-${WebsiteBucket}"
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName # Use the regional domain name to avoid redirects
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        DefaultCacheBehavior:
          TargetOriginId: !Sub "S3-${WebsiteBucket}"
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: ["GET", "HEAD", "OPTIONS"]
          CachedMethods: ["GET", "HEAD", "OPTIONS"]
          ForwardedValues:
            QueryString: false
            Cookies: { Forward: none }
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 0

  UserPreferencesUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-UserPool"
      UsernameAttributes: [email]
      AutoVerifiedAttributes: [email]
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true

  UserPreferencesUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${AWS::StackName}-AppClient"
      UserPoolId: !Ref UserPreferencesUserPool
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders: [COGNITO]
      CallbackURLs: [!Sub "https://${WebsiteDistribution.DomainName}/index.html", "http://localhost:8000/index.html"]
      LogoutURLs: [!Sub "https://${WebsiteDistribution.DomainName}/index.html", "http://localhost:8000/index.html"]
      AllowedOAuthFlows: [implicit, code]
      AllowedOAuthScopes: [openid, email, profile]

  TestScriptUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${AWS::StackName}-TestScriptClient"
      UserPoolId: !Ref UserPreferencesUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPreferencesUserPool
      Domain: !Sub "${AWS::StackName}-user-pool-${AWS::AccountId}"

  TestUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      UserPoolId: !Ref UserPreferencesUserPool
      Username: !Ref TestUserName
      UserAttributes:
        - Name: email
          Value: !Ref TestUserName
        - Name: email_verified
          Value: "true"

  # --- Nested Applications ---
  UserPrefsTitleIngestionApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: userprefs-title-ingestion.yaml
      Parameters:
        ProgramDataTableName: !Ref ProgrammesTable
        ProgramDataTableArn: !GetAtt ProgrammesTable.Arn
        WatchModeApiKeySecretArn: !Ref WatchModeApiKeySecret
        WatchModeHostname: !Ref WatchModeHostname
        ProgrammeDataStreamName: !If [ShouldCreateDataStream, !Ref ProgrammeDataStream, ""]
        ProgrammeDataStreamArn: !If [ShouldCreateDataStream, !GetAtt ProgrammeDataStream.Arn, ""]

  PeriodicReferenceApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: periodic-reference.yaml
      Parameters:
        ProgramDataTableName: !Ref ProgrammesTable
        ProgramDataTableArn: !GetAtt ProgrammesTable.Arn
        WatchModeApiKeySecretArn: !Ref WatchModeApiKeySecret
        WatchModeHostname: !Ref WatchModeHostname

  UserPreferencesApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: user-preferences.yaml
      Parameters:
        ProgramDataTableName: !Ref ProgrammesTable
        ProgramDataTableArn: !GetAtt ProgrammesTable.Arn
        UserPoolArn: !GetAtt UserPreferencesUserPool.Arn

  TitleRecommendationsConsumerApp:
    Type: AWS::Serverless::Application
    Condition: ShouldCreateDataStream
    Properties:
      Location: title-recommendations-consumer.yaml
      Parameters:
        ProgrammeDataStreamArn: !GetAtt ProgrammeDataStream.Arn
        ProgramDataTableName: !Ref ProgrammesTable
        ProgramDataTableArn: !GetAtt ProgrammesTable.Arn

  TitleEnrichmentApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: title-enrichment.yaml
      Parameters:
        ProgramDataTableName: !Ref ProgrammesTable
        ProgrammesTableStreamArn: !GetAtt ProgrammesTable.StreamArn
        WatchModeApiKeySecretArn: !Ref WatchModeApiKeySecret
        WatchModeHostname: !Ref WatchModeHostname

  WebApiApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: web-api.yaml
      Parameters:
        ProgramDataTableName: !Ref ProgrammesTable
        ProgramDataTableArn: !GetAtt ProgrammesTable.Arn
        UserPoolArn: !GetAtt UserPreferencesUserPool.Arn

  # --- New Admin Resources ---
  AdminLambdaExecutionRole:
     Type: AWS::IAM::Role
     Properties:
       RoleName: !Sub "${AWS::StackName}-AdminLambdaRole"
       AssumeRolePolicyDocument:
         Version: '2012-10-17'
         Statement:
           - Effect: Allow
             Principal:
               Service: lambda.amazonaws.com
             Action: sts:AssumeRole
       Policies:
         - PolicyName: AdminLambdaBasicExecution
           PolicyDocument:
             Version: '2012-10-17'
             Statement:
               - Effect: Allow
                 Action:
                   - logs:CreateLogGroup
                   - logs:CreateLogStream
                   - logs:PutLogEvents
                 Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-AdminLambda:*"
         - PolicyName: AdminLambdaDynamoDBAccess
           PolicyDocument:
             Version: '2012-10-17'
             Statement:
               - Effect: Allow
                 Action:
                   - dynamodb:DescribeTable
                   - dynamodb:ListTables
                 Resource: "*" # Restrict to specific tables if possible
         - PolicyName: AdminLambdaInvokeOtherLambdas
           PolicyDocument:
             Version: '2012-10-17'
             Statement:
               - Effect: Allow
                 Action:
                   - lambda:InvokeFunction
                 Resource: 
                   - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function/${AWS::StackName}-periodic-reference-PeriodicReferenceApp"
                   - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function/${AWS::StackName}-userprefs-title-ingestion-UserPrefsTitleIngestionApp"
                   - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function/${AWS::StackName}-title-enrichment-TitleEnrichmentApp"
                   # Add other Lambda ARNs as needed
 
   AdminLambdaFunction:
     Type: AWS::Serverless::Function
     Properties:
       FunctionName: !Sub "${AWS::StackName}-AdminLambda"
       CodeUri: event-streaming-app/src/admin_lambda/
       Handler: admin_lambda.lambda_handler
       Runtime: python3.11
       MemorySize: 128
       Timeout: 30
       Policies:
         - !Ref AdminLambdaExecutionRole
       Environment:
         Variables:
           PROGRAMMES_TABLE_NAME: !Ref ProgrammesTable
           PROGRAMMES_TABLE_ARN: !GetAtt ProgrammesTable.Arn
           REFERENCE_DATA_LAMBDA_NAME: !Sub "${AWS::StackName}-periodic-reference-PeriodicReferenceApp"
           TITLE_DATA_REFRESH_LAMBDA_NAME: !Sub "${AWS::StackName}-userprefs-title-ingestion-UserPrefsTitleIngestionApp"
           TITLE_ENRICHMENT_LAMBDA_NAME: !Sub "${AWS::StackName}-title-enrichment-TitleEnrichmentApp"
       Events:
         AdminApiGetSummary:
           Type: Api
           Properties:
             Path: /admin/system/dynamodb/summary
             Method: get
             RestApiId: !Ref ServerlessRestApi
         AdminApiPostReferenceRefresh:
           Type: Api
           Properties:
             Path: /admin/data/reference/refresh
             Method: post
             RestApiId: !Ref ServerlessRestApi
         AdminApiPostTitleRefresh:
           Type: Api
           Properties:
             Path: /admin/data/titles/refresh
             Method: post
             RestApiId: !Ref ServerlessRestApi
         AdminApiPostTitleEnrich:
           Type: Api
           Properties:
             Path: /admin/data/titles/enrich
             Method: post
             RestApiId: !Ref ServerlessRestApi
 
 # API Gateway definition (already present in the template)
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'" # Adjust for security
 
 # Authorizer definition would go here if needed for security

Outputs:
  UserPoolId:
    Description: "The ID of the Cognito User Pool"
    Value: !Ref UserPreferencesUserPool
  UserPoolClientId:
    Description: "The ID of the Cognito User Pool App Client for the web app"
    Value: !Ref UserPreferencesUserPoolClient
  TestScriptUserPoolClientId:
    Description: "The ID of the Cognito User Pool App Client for test scripts"
    Value: !Ref TestScriptUserPoolClient
  UserPoolDomain:
    Description: "The domain of the Cognito User Pool"
    Value: !Ref UserPoolDomain
  TestUsername:
    Description: "The username of the pre-created test user"
    Value: !Ref TestUserName
  ProgrammesTable:
    Description: "The name of the DynamoDB table for programmes"
    Value: !Ref ProgrammesTable
  WebsiteBucket:
    Description: "The S3 bucket hosting the website"
    Value: !Ref WebsiteBucket
  WebsiteUrl:
    Description: "The URL of the hosted website (CloudFront)"
    Value: !Sub "https://${WebsiteDistribution.DomainName}"
  WebsiteDistributionId:
    Description: "The ID of the CloudFront distribution"
    Value: !Ref WebsiteDistribution
  WebApiEndpoint:
    Description: "The Web API endpoint URL"
    Value: !GetAtt WebApiApp.Outputs.ApiEndpoint
  WebApiTestApiKey:
    Description: "The API key for testing the Web API"
    Value: !GetAtt WebApiApp.Outputs.WebApiTestApiKey
  UserPreferencesApiEndpoint:
    Description: "The User Preferences API endpoint URL"
    Value: !GetAtt UserPreferencesApp.Outputs.ApiEndpoint
  AdminApiEndpoint:
    Description: "The Admin API endpoint URL"
    Value: !Sub "https://${ServerlessRestApi.RestApiId}.execute-api.${AWS::Region}.amazonaws.com/Prod/admin"
