AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Root SAM application for the Event Streaming App.

Parameters:
  ProgrammesTableName:
    Type: String
    Description: Name of the DynamoDB table for programmes.
    Default: UKTVProgrammes
  WatchModeApiKey:
    Type: String
    NoEcho: true # Mark as NoEcho for sensitive parameters
    Description: "The API key for WatchMode API (will be stored in Secrets Manager)"
  WatchModeHostname:
    Type: String
    Description: "The Hostname for WatchMode API"
    Default: "https://api.watchmode.com"
  TestUserName:
    Type: String
    Description: "The username of the pre-created test user"
    Default: "test.user@example.com"
  CreateDataStream:
    Type: String
    Description: "Set to 'true' to create the Kinesis Data Stream. False if saving money and don't want to yet!"
    Default: "false"
    AllowedValues: [ "true", "false" ]

Conditions:
  ShouldCreateDataStream: !Equals [ !Ref CreateDataStream, "true" ]

Resources:
  WatchModeApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${AWS::StackName}/WatchModeApiKey"
      Description: API key for WatchMode API used by PeriodicReferenceFunction
      SecretString: !Ref WatchModeApiKey

  # DynamoDB Table for TV Programmes
  ProgrammesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref ProgrammesTableName
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"  # Partition key
        - AttributeName: "SK"
          KeyType: "RANGE" # Sort key
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  ProgrammeDataStream:
    Type: AWS::Kinesis::Stream
    Condition: ShouldCreateDataStream
    Properties:
      StreamModeDetails:
        StreamMode: ON_DEMAND

  # S3 Bucket for Website Hosting
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-website-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${WebsiteBucket.Arn}/*"

  # Cognito User Pool and Client
  UserPreferencesUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-UserPool"
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true

  UserPreferencesUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${AWS::StackName}-AppClient"
      UserPoolId: !Ref UserPreferencesUserPool
      GenerateSecret: false # Recommended for browser-based/mobile apps

  TestUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      UserPoolId: !Ref UserPreferencesUserPool
      Username: !Ref TestUserName
      UserAttributes:
        - Name: email
          Value: !Ref TestUserName
        - Name: email_verified
          Value: "true"

  # Nested application for the User Preferences driven title ingestion
  UserPrefsTitleIngestionApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: userprefs-title-ingestion.yaml
      Parameters:
        ProgramDataTableName: !Ref ProgrammesTable
        ProgramDataTableArn: !GetAtt ProgrammesTable.Arn
        WatchModeApiKeySecretArn: !Ref WatchModeApiKeySecret
        WatchModeHostname: !Ref WatchModeHostname
        ProgrammeDataStreamName: !If [ShouldCreateDataStream, !Ref ProgrammeDataStream, ""]
        ProgrammeDataStreamArn: !If [ShouldCreateDataStream, !GetAtt ProgrammeDataStream.Arn, ""]

  # Nested application for the Periodic Reference Data Lambda
  PeriodicReferenceApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: periodic-reference.yaml
      Parameters:
        ProgramDataTableName: !Ref ProgrammesTable
        ProgramDataTableArn: !GetAtt ProgrammesTable.Arn
        WatchModeApiKeySecretArn: !Ref WatchModeApiKeySecret
        WatchModeHostname: !Ref WatchModeHostname

  # Nested application for the User Preferences API Lambda
  UserPreferencesApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: user-preferences.yaml
      Parameters:
        ProgramDataTableName: !Ref ProgrammesTable
        ProgramDataTableArn: !GetAtt ProgrammesTable.Arn
        UserPoolArn: !GetAtt UserPreferencesUserPool.Arn # Pass the User Pool ARN to the nested app

  # Nested application for the Kinesis Consumer Lambda
  TitleRecommendationsConsumerApp:
    Type: AWS::Serverless::Application
    Condition: ShouldCreateDataStream # Only create if the stream exists
    Properties:
      Location: title-recommendations-consumer.yaml
      Parameters:
        ProgrammeDataStreamArn: !GetAtt ProgrammeDataStream.Arn
        ProgramDataTableName: !Ref ProgrammesTable
        ProgramDataTableArn: !GetAtt ProgrammesTable.Arn

  # Nested application for the Title Enrichment Lambda
  TitleEnrichmentApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: title-enrichment.yaml
      Parameters:
        ProgramDataTableName: !Ref ProgrammesTable
        ProgrammesTableStreamArn: !GetAtt ProgrammesTable.StreamArn
        WatchModeApiKeySecretArn: !Ref WatchModeApiKeySecret
        WatchModeHostname: !Ref WatchModeHostname

  # Nested application for the Web API Lambda
  WebApiApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: web-api.yaml
      Parameters:
        ProgramDataTableName: !Ref ProgrammesTable
        ProgramDataTableArn: !GetAtt ProgrammesTable.Arn
        UserPoolArn: !GetAtt UserPreferencesUserPool.Arn

Outputs:
  UserPoolId:
    Description: "The ID of the Cognito User Pool"
    Value: !Ref UserPreferencesUserPool
  UserPoolClientId:
    Description: "The ID of the Cognito User Pool App Client"
    Value: !Ref UserPreferencesUserPoolClient
  TestUsername:
    Description: "The username of the pre-created test user"
    Value: !Ref TestUserName
  ProgrammesTable:
    Description: "The name of the DynamoDB table for programmes"
    Value: !Ref ProgrammesTable
  WebsiteBucket:
    Description: "The S3 bucket hosting the website"
    Value: !Ref WebsiteBucket
  WebsiteUrl:
    Description: "The URL of the hosted website"
    Value: !GetAtt WebsiteBucket.WebsiteURL
  WebApiEndpoint:
    Description: "The Web API endpoint URL"
    Value: !GetAtt WebApiApp.Outputs.ApiEndpoint
  UserPreferencesApiEndpoint:
    Description: "The User Preferences API endpoint URL"
    Value: !GetAtt UserPreferencesApp.Outputs.ApiEndpoint