AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Web API Lambda for serving data to the SPA"

Parameters:
  ProgramDataTableName:
    Type: String
  ProgramDataTableArn:
    Type: String
  UserPoolArn:
    Type: String
  StageName:
    Type: String
    Default: Prod

Resources:
  WebApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Cors:
        AllowMethods: 'GET,POST,PUT,DELETE,OPTIONS'
        AllowHeaders: 'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'
        AllowOrigin: '*'
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref UserPoolArn
        ApiKeyRequired: true # Require an API key on all routes by default
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: !Sub "${AWS::StackName}-web-api-usage-plan"


  WebApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: web_api.lambda_handler
      Runtime: python3.12
      CodeUri: ../../src/web_api/
      MemorySize: 256
      Timeout: 30
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:GetItem
                - dynamodb:BatchWriteItem
                - dynamodb:BatchGetItem
                - dynamodb:Scan
              Resource: !Ref ProgramDataTableArn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref ProgramDataTableName

          AWS_ENDPOINT_URL: "" # for testing
      Events:
        GetSources:
          Type: Api
          Properties:
            RestApiId: !Ref WebApi
            Path: /sources
            Method: get
            Auth:
              Authorizer: NONE
              ApiKeyRequired: false # This is a public endpoint
        GetGenres:
          Type: Api
          Properties:
            RestApiId: !Ref WebApi
            Path: /genres
            Method: get
            Auth:
              Authorizer: NONE
              ApiKeyRequired: false # This is a public endpoint
        GetTitles:
          Type: Api
          Properties:
            RestApiId: !Ref WebApi
            Path: /titles
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
        GetRecommendations:
          Type: Api
          Properties:
            RestApiId: !Ref WebApi
            Path: /recommendations
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
        GetPreferences:
          Type: Api
          Properties:
            RestApiId: !Ref WebApi
            Path: /preferences
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
        UpdatePreferences:
          Type: Api
          Properties:
            RestApiId: !Ref WebApi
            Path: /preferences
            Method: put
            Auth:
              Authorizer: CognitoAuthorizer

Outputs:
  ApiEndpoint:
    Description: "Web API Gateway endpoint URL for the Prod stage"
    Value: !Sub "https://${WebApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  WebApiFunctionName:
    Description: "Name of the Web API Lambda function"
    Value: !Ref WebApiFunction
  WebApiTestApiKey:
    Description: "The API key for testing the Web API"
    Value: !Ref WebApi.ApiKey
  WebApiFunctionArn:
    Description: "ARN of the Web API Lambda function"
    Value: !GetAtt WebApiFunction.Arn
