# /resources/cloudformation/web-api.yaml

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Web API Lambda for serving data to the SPA"

Parameters:
  ProgramDataTableName:
    Type: String
  ProgramDataTableArn:
    Type: String
  UserPoolArn:
    Type: String
  StageName:
    Type: String
    Default: Prod

Resources:
  # Lambda backing the web api
  WebApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: web_api.lambda_handler
      Runtime: python3.12
      CodeUri: ../../src/web_api/
      MemorySize: 256
      Timeout: 30
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:GetItem
                - dynamodb:BatchWriteItem
                - dynamodb:BatchGetItem
                - dynamodb:Scan
              Resource: !Ref ProgramDataTableArn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref ProgramDataTableName
          AWS_ENDPOINT_URL: "" # for testing
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
            RestApiId: !Ref WebApi

  # The API Gateway for the Web API
  WebApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${StageName}
      # Add a global CORS configuration to handle preflight requests and add CORS headers.
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: "Usage plan for WebApi"

      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: "UK TV Guide Web API"
          version: "1.0"
        paths:
          # --- Public Endpoints ---
          /sources:
            get:
              summary: "Get all available sources"
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebApiFunction.Arn}/invocations"
              responses:
                "200":
                  description: "A list of all available sources"
          /genres:
            get:
              summary: "Get all available genres"
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebApiFunction.Arn}/invocations"
              responses:
                "200":
                  description: "A list of all available genres"

          # --- Protected Endpoints ---
          # These endpoints require BOTH a Cognito JWT for user authentication
          # AND an API Key for usage plan tracking.
          # UPDATE: The API Key requirement has been set to false (`x-amazon-apigateway-api-key-required: false`).
          # This allows the browser-based Single Page Application (SPA) to call these endpoints
          # without embedding a secret API key. The Cognito JWT remains the primary security
          # mechanism for authenticating the user. API keys can still be sent by other clients
          # (like test scripts) and will be tracked by the Usage Plan.
          /titles:
            get:
              summary: "Get titles based on user preferences"
              security:
                - CognitoAuthorizer: []
              x-amazon-apigateway-api-key-required: false
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebApiFunction.Arn}/invocations"
              responses:
                "200":
                  description: "A list of titles matching user preferences"
          /recommendations:
            get:
              summary: "Get new recommendations for the user"
              security:
                - CognitoAuthorizer: []
              x-amazon-apigateway-api-key-required: false
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebApiFunction.Arn}/invocations"
              responses:
                "200":
                  description: "A list of new recommendations"
          /preferences:
            get:
              summary: "Get user preferences"
              security:
                - CognitoAuthorizer: []
              x-amazon-apigateway-api-key-required: false
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebApiFunction.Arn}/invocations"
              responses:
                "200":
                  description: "User's preferences"
            put:
              summary: "Update user preferences"
              security:
                - CognitoAuthorizer: []
              x-amazon-apigateway-api-key-required: false
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebApiFunction.Arn}/invocations"
              responses:
                "200":
                  description: "Confirmation of update"

        components:
          securitySchemes:
            # Security scheme for authenticating end-users via Cognito.
            # The JWT is passed in the 'Authorization' header.
            # This provides the user's identity ('sub' claim) to the backend Lambda.
            CognitoAuthorizer:
              type: "apiKey"
              name: "Authorization"
              in: "header"
              x-amazon-apigateway-authtype: "cognito_user_pools"
              x-amazon-apigateway-authorizer:
                type: "cognito_user_pools"
                providerARNs:
                  - !Ref UserPoolArn

            # This defines that an API key is expected in the 'x-api-key' header.
            # It is not used as a direct authorizer, but enables the 'x-amazon-apigateway-api-key-required: true'
            # property on methods, which links them to a Usage Plan for throttling and quotas.
            ApiKeyAuthorizer:
              type: "apiKey"
              name: "x-api-key" # Standard header for API keys
              in: "header"

  WebApiTestApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${AWS::StackName}/WebApiTestApiKey"
      Description: API key for Web API testing
      SecretString: !Ref WebApi.ApiKey

Outputs:
  ApiEndpoint:
    Description: "Web API Gateway endpoint URL for the Prod stage"
    Value: !Sub "https://${WebApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  WebApiFunctionName:
    Description: "Name of the Web API Lambda function"
    Value: !Ref WebApiFunction
  WebApiTestApiKey:
    Description: "The API key for testing the Web API"
    Value: !Ref WebApi.ApiKey
  WebApiFunctionArn:
    Description: "ARN of the Web API Lambda function"
    Value: !GetAtt WebApiFunction.Arn
