# /resources/user-preferences-api-simple.yaml

openapi: "3.0.1"
info:
  title: "UK TV Guide User Preferences API (Simplified)"
  version: "1.0"
paths:
  /preferences:
    get:
      summary: "Get the authenticated user's preferences"
      security:
        - CognitoAuthorizer: []
      # This block now defines the backend integration for this specific path.
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST" # This must be POST for Lambda integrations
        # This syntax references the stage variable we defined in the parent template.
        # It is clean, valid YAML and avoids the !Sub parsing error.
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${stageVariables.LambdaFunctionArn}/invocations"
      responses:
        "200":
          description: "A list of the user's preferences"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  securitySchemes:
    CognitoAuthorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools