amazon:
  dynamodb:
    tableName: products
    endpoint: ${DYNAMODB_ENDPOINT:}  # Empty default for AWS
  accessKeyId: ${AWS_ACCESS_KEY_ID:key}
  secretKey: ${AWS_SECRET_ACCESS_KEY:key2}
  region: eu-west-2

server:
  port: 8080

spring:
  application:
    name: product-api