AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: java-ddb-product-api
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  ProductApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ProductApiFunction
      Handler: product.ProductApiApp::handleRequest
      Runtime: java21
      Architectures:
      - x86_64
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMO_TABLENAME: "default_table_from_template" # Add this line
      Events:
        GetSpecificProduct:
          Type: Api
          Properties:
            Path: /api/v1/products/{id}
            Method: get
        GetAllProducts:
          Type: Api
          Properties:
            Path: /api/v1/products
            Method: get
        AddNewProduct:
          Type: Api
          Properties:
            Path: /api/v1/products
            Method: post
        UpdateProduct:
          Type: Api
          Properties:
            Path: /api/v1/products/{id}
            Method: put
        DeleteProduct:
          Type: Api
          Properties:
            Path: /api/v1/products/{id}
            Method: delete

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductDDBTable

  ProductDDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: products
      PrimaryKey:
        Name: id
        Type: String

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ProductApi:
    Description: API Gateway endpoint URL for Prod stage for Product API function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/v1/products/"
  ProductApiFunction:
    Description: Product API Lambda Function ARN
    Value: !GetAtt ProductApiFunction.Arn
  ProductApiFunctionIamRole:
    Description: Implicit IAM Role created for Product API function
    Value: !GetAtt ProductApiFunction.Arn
