AWSTemplateFormatVersion: '2010-09-09'
Description: EKS Cluster with ECR Registry

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: The CIDR block for the VPC

  Subnet1Cidr:
    Type: String
    Default: 10.0.1.0/24
    Description: The CIDR block for Subnet1

  Subnet2Cidr:
    Type: String
    Default: 10.0.2.0/24
    Description: The CIDR block for Subnet2

  Subnet3Cidr:
    Type: String
    Default: 10.0.3.0/24
    Description: The CIDR block for Subnet3

  VpcName:
    Type: String
    Default: vpc-eks-basic
    Description: The name of the VPC

  Subnet1Name:
    Type: String
    Default: snet-eks-basic-1
    Description: The name of Subnet1

  Subnet2Name:
    Type: String
    Default: snet-eks-basic-2
    Description: The name of Subnet2

  Subnet3Name:
    Type: String
    Default: snet-eks-basic-3
    Description: The name of Subnet3

  EKSClusterName:
    Type: String
    Default: eks-basic
    Description: The name of the EKS Cluster

  NodeGroupName:
    Type: String
    Default: eks-basic-nodes
    Description: The name of the EKS Node Group

  ECRRepositoryName:
    Type: String
    Default: ecr-basic
    Description: The name of the ECR Repository

  DesiredCapacity:
    Type: Number
    Description: Desired number of worker nodes
    Default: 2
    MinValue: 1
    MaxValue: 10

  NodeInstanceType:
    Type: String
    Description: EC2 instance type for the worker nodes (For small EKS nodes, consider using burstable instance types like t3.small, t3.medium, or t3.large, or general-purpose instances like m5.large or m6i.large)
    Default: t3.small

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref VpcName

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref Subnet1Cidr
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Ref Subnet1Name

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref Subnet2Cidr
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Ref Subnet2Name

  Subnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref Subnet3Cidr
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Ref Subnet3Name

  EKSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EKS Cluster security group
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: !Sub ${EKSClusterName}-role
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: Allow
            Principal: 
              Service: 
                - eks.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

  EKSNodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - ec2.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

  EKSAdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::503561418276:user/iamadmin
                - arn:aws:sts::503561418276:assumed-role/AWSReservedSSO_PowerUserAccess_5664d530bb559f9a/awsnotesic
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref EKSClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          - !Ref Subnet1
          - !Ref Subnet2
          - !Ref Subnet3
        SecurityGroupIds:
          - !Ref EKSSecurityGroup

  NodeGroup:
      Type: AWS::EKS::Nodegroup
      Properties:
        ClusterName: !Ref EKSClusterName
        NodegroupName: !Ref NodeGroupName
        NodeRole: !GetAtt EKSNodeInstanceRole.Arn
        Subnets: 
          - !GetAtt Subnet1.Id
          - !GetAtt Subnet2.Id
          - !GetAtt Subnet3.Id
        ScalingConfig:
          DesiredSize: !Ref DesiredCapacity
          MinSize: 1
          MaxSize: 10
        InstanceTypes:
          - !Ref NodeInstanceType

  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECRRepositoryName

Outputs:
  EKSClusterName:
    Description: The name of the EKS Cluster
    Value: !Ref EKSCluster

  ECRRepositoryUri:
    Description: The URI of the ECR Repository
    Value: !GetAtt ECRRepository.RepositoryUri

  EKSClusterEndpoint:
    Description: The endpoint for the EKS Cluster
    Value: !GetAtt EKSCluster.Endpoint