name: AWS Authentication

on:
  workflow_dispatch:
    inputs:
      cloudformation_template_folder:
        description: 'CloudFormation template file'
        required: true
        default: 'vpc'
      cloudformation_stack_name:
        description: 'CloudFormation stack name'
        required: true
        default: 'simple-vpc'
      cloudformation_action:
        description: 'CloudFormation action to perform'
        required: true
        default: 'create'

jobs:
  aws-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: us-east-1

      - name: Verify AWS authentication
        run: aws sts get-caller-identity

      - name: Perform CloudFormation Create Stack
        if: ${{github.event.inputs.cloudformation_action}} == "create"
        run: |
          aws cloudformation create-stack \
            --stack-name ${{github.event.inputs.cloudformation_stack_name}} \
            --template-body file://${{github.event.inputs.cloudformation_template_folder}}/${{github.event.inputs.cloudformation_stack_name}}-cfn.yaml \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Perform CloudFormation Delete Stack
        if: ${{github.event.inputs.cloudformation_action}} == "delete"
        run: |
          aws cloudformation delete-stack --stack-name ${{github.event.inputs.cloudformation_stack_name}}