name: AWS CloudFormation

on:
  workflow_dispatch:
    inputs:
      cloudformation_template_folder:
        description: 'CloudFormation template file'
        required: true
        default: 'network'
      cloudformation_stack_name:
        description: 'CloudFormation stack name'
        required: true
        default: 'simple-vpc'
      cloudformation_action:
        description: 'CloudFormation action to perform (apply or delete)'
        required: true
        default: 'apply'

jobs:
  aws-cfn:
    permissions:
      id-token: write # to request tokens for AWS CLI
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ${{vars.AWS_REGION}}

      - name: "DEBUG: print workflow inputs"
        run: |
          echo "cloudformation_template_folder == ${{github.event.inputs.cloudformation_template_folder}}"
          echo "cloudformation_stack_name == ${{github.event.inputs.cloudformation_stack_name}}"
          echo "cloudformation_action == ${{github.event.inputs.cloudformation_action}}"    

      - name: CloudFormation Create or Update Stack
        if: github.event.inputs.cloudformation_action == 'apply'
        run: |
          echo "Action == ${{github.event.inputs.cloudformation_action}}"
          if aws cloudformation describe-stacks --stack-name ${{github.event.inputs.cloudformation_stack_name}} --region ${{vars.AWS_REGION}}; then
            echo "Stack exists, updating..."
            aws cloudformation update-stack \
              --stack-name ${{github.event.inputs.cloudformation_stack_name}} \
              --template-body file://resources/${{github.event.inputs.cloudformation_template_folder}}/${{github.event.inputs.cloudformation_stack_name}}-cfn.yaml \
              --capabilities CAPABILITY_NAMED_IAM \
              --region ${{vars.AWS_REGION}}
          else
            echo "Stack does not exist, creating..."
            aws cloudformation create-stack \
              --stack-name ${{github.event.inputs.cloudformation_stack_name}} \
              --template-body file://resources/${{github.event.inputs.cloudformation_template_folder}}/${{github.event.inputs.cloudformation_stack_name}}-cfn.yaml \
              --capabilities CAPABILITY_NAMED_IAM \
              --region ${{vars.AWS_REGION}}
          fi

      - name: CloudFormation Delete Stack
        if: github.event.inputs.cloudformation_action == 'delete'
        run: |
          echo "Delete == ${{github.event.inputs.cloudformation_action}}"
          aws cloudformation delete-stack \
            --stack-name ${{github.event.inputs.cloudformation_stack_name}} \
            --region ${{vars.AWS_REGION}}

      - name: CloudFormation Describe Stack
        run: |
          aws cloudformation describe-stacks \
            --stack-name ${{github.event.inputs.cloudformation_stack_name}} \
            --region ${{vars.AWS_REGION}}